# Generated by Django 3.0.3 on 2020-03-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='students',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
