# Generated by Django 3.0.3 on 2020-03-10 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('software', '0003_auto_20200309_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Labname', models.CharField(max_length=20)),
                ('software', models.BooleanField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='software.Building')),
            ],
        ),
    ]
