# Generated by Django 3.0.3 on 2020-03-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('software', '0004_labs'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='Lab',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Labs',
        ),
    ]
